title: Azure Landing Zone
description: Cloud-Native Azure development
author:
  name: Vincent ter Maat

remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true

minima:
  skin: auto
  social_links:
      - { platform: github,          user_url: "https://github.com/vincenttermaat" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/in/vincent-ter-maat" }
  header_pages:
  - about.md