title: Azure Landing Zone
description: Cloud-Native Azure development
author:
  name: Vincent ter Maat
  
remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-theme-primer
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

github_username: vincenttermaat
