title: Azure Landing Zone
description: Cloud-Native Azure development
author:
  name: Vincent ter Maat
  
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

github_username: vincenttermaat
