title: Azure Landing Zone
description: Cloud-Native Azure development
author:
  name: Vincent ter Maat
  
remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

github_username: vincenttermaat
